# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!
target 'test-sm4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test-sm4

pod 'FMDB/SQLCipher'


end
